from typing import List, Optional
from thinc.types import Floats2d

def chu_liu_edmonds(scores: Floats2d, root_vertex: int) -> List[Optional[int]]: ...

def mst_decode(scores: Floats2d) -> List[Optional[int]]: ...
